### ISSUE TITLE
Word wrapping changes location

### ISSUE THREAD

**Issue by asdofindia** [knadh/floatype.js#1]
![Screenshot_2023-12-09-23-20-20-69_3aea4af51f236e4932235fdada7d1643](https://github.com/knadh/floatype.js/assets/945777/709f1793-0b28-4200-9015-e1176c373e82)

https://github.com/yuku/textcomplete/tree/main/packages/textcomplete-textarea is using https://www.npmjs.com/package/textarea-caret which said in the readme that it copies text after the caret too to consider word wrap complication and that's why I tried this.

But I think the issue here is rather about that math.max not detecting that a new line has started because of word wrap.

I suppose if the y coordinate of selection start is higher than y coordinate of space/newline, then we have to assume word has wrapped and probably set x coordinate to extreme left.

**Comment by knadh** [comment]
Good spot!

> But I think the issue here is rather about that math.max not detecting that a new line has started because of word wrap.

This isn't the case. Automatic word-wrapping is purely a visual artifact and doesn't introduce a "\n" in the value.

**Comment by asdofindia** [comment]
Yes, and that's why it doesn't "detect" it when looking for \n
