### ISSUE TITLE
Method to kill / enable.

### ISSUE THREAD

**Issue by MarketingPip** [knadh/floatype.js#4]
A method to kill event listener and reinitialize this would be ideal for turning auto completions on or off. 

Currently when using something like a 

```
kill: function(){
destroy()
}
```

and re-enabling causes a bug / issue where textbox does not appear in correct position. Example below:

![image](https://github.com/knadh/floatype.js/assets/86180097/d61d794a-f935-48bd-9daf-3cd5f0ba322e)

I suggest

```js
.kill() // to stop instance and listeners.  
.enable() // to enable listeners. 
```

**Comment by knadh** [comment]
This is done in https://github.com/knadh/floatype.js/commit/3fe56ff4635e52d6b1733bb88e431894a3637309.

`const f = floatype(..)` to initialize. `f.unbind()` to unbind/remove the listeners.

**Comment by MarketingPip** [comment]
@knadh again - that does NOT work... and causes ^ the above issue..........

**Comment by knadh** [comment]
Ouch, fixed this. You can see the demo here: https://knadh.github.io/floatype.js/

**Comment by MarketingPip** [comment]
@knadh - ah I was wondering what I was missing hahahah! I will try to make a PR on this to improve somethings. Might drop code here etc for you to look out. Helps grab multiple words (tho could be done via a render / demo via render). Plus I extracted Ace Editor's template for auto completions, which would be nice to have a custom set template to set completions from a JSON like so.

```js
{"ShipIt":"some value set here etc...."}
```
